### ISSUE TITLE
Audio popping due to compressor upward

### ISSUE THREAD

**Issue by dull4h4n** [Digitalone1/PulseEffects-Presets#1]
I disabled each effect and only with upward compressor do I get a pop sound when initiating audio. Is there any way to prevent this? This does not occur with auto gain, but as you stated, its not ideal.

**Comment by Digitalone1** [comment]
Hi, it's because upward compressor raises the signal level above 0 db. That occurs in almost any plugin of the preset and its adjusted by the limiter at the end, but you disabled it.

To prevent this with upward compressor only enabled, decrease its output level (the bottom bar).

**Comment by Digitalone1** [comment]
I read your message better and you're talking about a popping sound only at the start, right?

I get this even with the whole present sometimes and I think it's how upward compressor works. Maybe it's reduced playing with different values of attack and release.

**Comment by Digitalone1** [comment]
Made some tests, reducing the attack, the popping is reduced also.

**Comment by dull4h4n** [comment]
Reducing the attack makes the pop briefer and maybe softer, but it still doesnt eliminate it. Auto-gain seems to eliminate altogether, particularly with detect silence enabled. I do prefer the quality of the compressor over autogain, I just cant take the startling pop as i stop and start media. Wish I could fix.

**Comment by Digitalone1** [comment]
Try to reduce release also, but I think nothing can be done, that's how upward compressor works.

**Comment by Digitalone1** [comment]
I updated a new version with attack to 0 ms in order to reduce initial popping sound.

**Comment by Digitalone1** [comment]
@dull4h4n I updated a new preset with lookahead in upward compressor that greatly reduce this issue. Tested for long time, it's way better than before. Also changed timings between compressor and the gate to reduce the noise amplification.

Please, test if you would. I will close this issue in the future.

**Comment by dull4h4n** [comment]
Ive only used it a bit but so far no popping at the start of audio. I do notice the default volume seems a little low and it requires me to turn up system volume by about 20% over default or my previous preset. Which values would I increase to best raise baseline volume?

**Comment by Digitalone1** [comment]
Threshold in the upward compressor was decreased because in the previous version sometimes low volume parts sounded stronger than the high ones while with this new preset it should be more balanced.

Raise the threshold up to -8 db. No more because there will be clipping. In case of clipping you should also adjust the limiter input level.

**Comment by dull4h4n** [comment]
Seems to work well. Thanks for the preset.
