### ISSUE TITLE
Error: Preset not loaded correctly

### ISSUE THREAD

**Issue by regulator-g** [Digitalone1/PulseEffects-Presets#10]
Hi there, when i try to load LoudnessEqualizer I get the error "preset not loaded correctly" "wrong format in effects list"

-I am using EasyEffects flatpak version (6.3.0)
-I put the file in the right folder as per instructions, preset appears in list etc, error appears when clicking load
-Pop_OS
-i can make basic effects and save as my own preset

not sure what Im doing wrong, please help :)

**Comment by Digitalone1** [comment]
Hello, it's likely you saved the preset the wrong way.

Follow instructions [here](https://github.com/Digitalone1/EasyEffects-Presets#how-to-download).

> Click on Code button and download the zip archive. Extract it on your system and pick the preset you need. You can also clone the git repository. Every other method you use, especially if you go in the preset page and right-click Save As, might result in a corrupted and not working file.

**Comment by regulator-g** [comment]
> Hello, it's likely you saved the preset the wrong way.
> 
> Follow instructions [here](https://github.com/Digitalone1/EasyEffects-Presets#how-to-download).
> 
> > Click on Code button and download the zip archive. Extract it on your system and pick the preset you need. You can also clone the git repository. Every other method you use, especially if you go in the preset page and right-click Save As, might result in a corrupted and not working file.

thanks it's working now, sorry I skipped over the "how to download" section and just grabbed the json file

**Comment by Digitalone1** [comment]
No worries.
