### ISSUE TITLE
JSON format error?

### ISSUE THREAD

**Issue by Jolleboll** [Digitalone1/PulseEffects-Presets#14]
Hello, I try to import the preset and get the following:

"PRESET NOT LOADED CORRECTLY"
"Wrong Format in Effects List"

Running EasyEffects 7.1.4

Big thanks in advance. All the presets I find with Google suffering from this problem.

**Comment by Digitalone1** [comment]
Hello. It's likely you download them the wrong way. Click on the `Code` button and download the zip package. Then extract it in a local folder and import the `.json` file from EasyEffects.

**Update:** Anyway in latest versions, only `LoudnessEqualizer.json` can be imported correctly.

**Comment by Jolleboll** [comment]
Oh wow, why... why is it like this!? Is the .carxp file required? And why would wget on the direct GitHub json file link make a mess of the file contents?!

Anyway it works now, thank you so much for speedy help!!

Joel

**Comment by Digitalone1** [comment]
> Oh wow, why... why is it like this!? Is the .carxp file required? And why would wget on the direct GitHub json file link make a mess of the file contents?!

That file is for Carla software. It's all written in the README. Probably wget downloads the HTML files.
