### ISSUE TITLE
Installation instructions for FlatPak

### ISSUE THREAD

**Issue by edent** [Digitalone1/PulseEffects-Presets#2]
I've placed the JSON in `~/.config/PulseEffects/output/` but it doesn't appear in PulseEffects. I've restarted my machine.

I'm running PulseEffects 4.8.2 on Pop OS 20.10.  It didn't have a `~/.config/PulseEffects/` directory, so I created one, but the preset never appeared.  I *think* this is because I've installed it as a FlatPak.

So, I placed it in `~/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects/output/` restarted it, and it worked.

I'll drop in a PR to update the README.

**Comment by Digitalone1** [comment]
Didn't know about Flatpak. Thank you.

**Comment by edent** [comment]
No worries. And thanks for the preset. It has made my conference calls *so* much more pleasant.
