### ISSUE TITLE
Calf JACK host

### ISSUE THREAD

**Issue by kopr12** [Digitalone1/PulseEffects-Presets#5]
Can you provide preset file for Calf Jack Host (Calf Plugin Pack for Jack) ?
I'm using Jack but can't use Carla (compile issues)

Edit: Never mind, I've managed to compile Carla and open preset.
But still, it would be nice if you can provide preset for Calf as well.

**Comment by Digitalone1** [comment]
Sorry, I don't use it.

You could try to run EasyEffects and reproduce the settings in Calf Jack Host.

**Comment by kopr12** [comment]
No problems, I just finished setting it up, had to clone each plugin 5 times, for use with 5.1 speakers and the result is spectacular.

![20220512-043207](https://user-images.githubusercontent.com/11412353/167980412-1000468d-f55c-40ec-8b39-dab6133cf957.png)

It's great btw, fantastic job :+1: 

I'll close the issue, thanks again!

**Comment by Digitalone1** [comment]
@TheMainMMan I just watched the screenshot. Can't you simply use the mono version of every plugin rather than doubling the stream to fee every right/left input?

**Comment by kopr12** [comment]
Good point, thanks for the tip, didn't think of that, because that's what the preset opened by default and I just rushed through it to see how it sounds, I'll try that in a minute.
Had to quit on it to be honest, because it was taxing the cpu too much, and the memory usage of Carla was also pretty high, with other compressors I've tried that wasn't the case, with mono versions that might be different but I guess I would have to manually setup all of them, which might be very tedious.

**Comment by kopr12** [comment]
I modified `LoudnessEqualizer.carxp` and replaced `stereo` with `mono` , it works and it's easier with cpu thean stereo one, but it's still high, I mean I have a good system and I don't feel that at all , but still it bothers me, I'm not sure if that's because of Carla or LSP plugins, system monitor just shows that it's Carla.
Some options btw could not be found for mono plugins, I also set `force stereo` to `false`
It works but I think stereo version was better, for some reason.
Maybe I'll try to re-create it in Calf and see will it perform better.

![20220513-230102](https://user-images.githubusercontent.com/11412353/168390271-6e97034d-12cb-4bf6-bcfc-4fae689a599a.png)
![20220513-230133](https://user-images.githubusercontent.com/11412353/168390278-ca843df5-0f51-4509-9f68-950a23e565df.png)

**Comment by Digitalone1** [comment]
Do you run Carla in hidden mode at startup?

Try also the Calf Mono Gate rather than the LSP one, I always found it better. Or at least, I set it in a better way because I use EasyEffects mainly. You can pick its settings from the EasyEffects preset.

**Comment by kopr12** [comment]
No I don't. First time I'm using Carla actually, will have to play with it and study it more closely. I use Catia and Calf plugins, with Jack, I have PulseAudio bridged in Jack and I don't use Pipewire. 

I will try that, also I'll try LSP plugins but in Catia, just to exclude Carla maybe as a culprit. Didn't have much time to see the settings in each plugin and set it manually, which I should be doing anyway, presets are much easier of course, but I will try that over weekend. If I find something interesting I will let you know.

**Comment by kopr12** [comment]
Did some testing and it's not Carla but LSP plugins, I just loaded Mono compressor plugin, just one instance, in Catia (I use this one with Calf compressor btw) and the cpu is using around 30%, with Calf compressor it's 4% max (with 6 of them running in Calf Studio)
Anyway that's not your problem, I made this issue because I couldn't get Carla to run and it's not in the repos (I'm on Gentoo btw) , found it later from other sources but it wouldn't compile, then I asked you for Calf presets, because it's easy to provide them if you're using Calf, then I found another source for Carla and that one compiled, your preset sounds really great, but LSP plugins are not working for me as I would like, I can replicate that but it would take some time, if I make it in the end I'll post a PR and maybe you can provide Calf Studio preset as well, I don't think though that you can make upward compressor with Calf, but I'm not sure, not sure about other stuff for that matter, anyway it doesn't really matter in the end, your main target is pipewire and easyeffects, so that's that.

**Comment by kopr12** [comment]
I don't know why I didn't think of this sooner, but I can clone the plugins only 3 times, instead of 6, and it works as it should, but with less overhead.

![20220515-220908](https://user-images.githubusercontent.com/11412353/168492365-f1d77317-fa10-445f-a489-2a5c78a00b46.png)

**Comment by Digitalone1** [comment]
Nice, but while it makes sense for front/rear left/right channels, LFE and front center are quite different, so for them you could use mono versions.

**Comment by kopr12** [comment]
For sure, I didn't get to the part where I configure LFE separately, yet.
Right now I'm using your preset, but since that now I can open the UI of the LSP plugins, I can see more clearly what is set and I'm trying to re-create that with Calf plugins, some options are different (not available in Culf), most difficult is upward compressor, at the moment I'm just boosting the Input signal, could also do it with Makeup Gain, it sounds good in the end but I'll have to play with it more. LSP plugins are very good but I like the Calf UI much better.

**Comment by kopr12** [comment]
Sorry if I bother you, but I was wondering how would you configure some other plugin than LSP, which doesn't have Upward mode, to act as a upward compressor, say Calf compressor for example?
![20220517-182352](https://user-images.githubusercontent.com/11412353/168861751-392f5b86-952d-4365-b1d6-936d6df22c69.png)

**Comment by Digitalone1** [comment]
There's no way. The upward compression uses a special method to boost the signal based on ratio and threshold level, you can't do it just amplifying the signal, because in upward compression generally the signal is only amplified when it's below the threshold.

Unfortunately Calf plugins do only downward compression.

**Comment by kopr12** [comment]
I know, but the end result isn't that bad, I'm pretty satisfied with it.
Okay, thanks.
