### ISSUE TITLE
Also desn'a work for me

### ISSUE THREAD

**Issue by Miroslav11** [Digitalone1/PulseEffects-Presets#6]
I have flatpak version of easyeffects for pipewire and I've put your script "LoudnessEqualizer.json" inside "/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output" but it's not working.

Also your instructions are not really clear. Do we need to add effects manually inside easyeffects, and what effects and in what order?

I have latest flatpak version 6.2.5, and PipeWire 0.3.51

**Comment by Digitalone1** [comment]
Hello, I don't use the Flatpak version, so I don't know which is the exact config folder, but the one you mentioned should be correct.

Once you put the preset file (it's not a script) inside the config folder, the related preset should be visible in the preset menu (the leftmost button in the header bar, I don't know which language you are running, but in English version that button has "Preset" label).

Once opened that menu you should locale the "LoudnessEqualizer" preset inside the Output section. Click on the load button to apply it, no need to care about effects order or other parameters (anyway the stream goes from the highest effects to the lowest inside the list).

If you ensure the folder you mentioned is correct, I will update the README for Flatpak users. Please, let me know.

**Comment by Miroslav11** [comment]
yep, figure it out. It's correct path for flatpak, but when I click "Load" nothing happens

**Comment by Digitalone1** [comment]
> yep, figure it out. It's correct path for flatpak, but when I click "Load" nothing happens

Don't you see the left side list filled by effects like the screenshot below?

![image](https://user-images.githubusercontent.com/25790525/168420116-183a8a2a-8250-4009-87ee-a8d2db681375.png)

The effects should be in the following order: Gate -> Compressor -> Multiband Compressor -> Equalizer -> Limiter

**Comment by Miroslav11** [comment]
nope, it's not filling when I hit "Load". Unfortunately Ubuntu and derivatives don't have .deb version of easyeffects.
I think maybe it has something with permissions for Flatpak version. That's my suspicion anyway

**Comment by Digitalone1** [comment]
In this case, please, open a new Issue [here](https://github.com/wwmm/easyeffects/issues) and specify that you cannot add Effects to the list. Should be an issue related to Flatpak.

**Comment by Miroslav11** [comment]
will do. Thanks

**Comment by Digitalone1** [comment]
Solved.
